### ISSUE TITLE
PySCFDriver.run() running forever

### ISSUE THREAD

**Issue by anbonimus** [Qiskit/qiskit-nature#1007]
### Environment

- **Qiskit Nature version**:0.36.2
- **Python version**: 3.8
- **Operating system**: Linus

### What is happening?

I am doing some test runs of He2 molecule with PySCFDriver. The function worked well when I used basis set such as 6-31g and ccpvtz. but when I use basis sets such as ccpvqz and ccpv5z, the run() function takes forever to run. I also cannot kill the program with ctrl+c, I have to stop it with crtl+z instead. I also tried ran it with super computers, but with 84 CPUs and 10hrs, I still got nothing from run() function. Are the basis sets the problem here? But the are supported by pyscf so they should also be supported here right?

### How can we reproduce the issue?

'''
driver = PySCFDriver(atom = 'he; he 1 ' + str(r), unit = UnitsType.ANGSTROM, basis = 'ccpv5z', init_guess = InitialGuess.ONE_E)

print('1')

molecule = driver.run()

print('2')
'''
str(r) is the bond length and it should work for any number.

### What should happen?

I tried to see who is the problem by letting the program print number 1 and 2 after each function call. Output will be just number 1 and it never goes to 2, which indicates that run() function is taking forever to run.

**Comment by mrossinek** [comment]
Scaling up the problem like this will obviously cause the time to solution increase significantly. The `PySCFDriver` is merely wrapping the PySCF code in a minimal way. If PySCF on its own is able to find the solution significantly faster I would consider this a bug, but given your description I do not believe this to be the case.

I would suggest that you try to solve this problem using PySCF on its own (without the driver wrapping it) to see if this performs better. Since you appear to have access to a super computer, https://github.com/pyscf/mpi4pyscf might prove useful to you. If this does not work or if you need help, I suggest that you reach out to the PySCF community.

When doing the above, be sure to save a `chkfile` which you can then provide to the `PySCFDriver` as input. This will restart from a converged calculation and should allow you to do the heavy work only once and then re-use it.

<hr/>

A final note: `Ctrl+Z` normally means "send to background". So you may want to double check whether you really "killed" the job or merely hid it away. Cancelling via `Ctrl+C` might require you to send the key sequence repeatedly (because of the nested program run) and it the program might only register it after some time because it only checks for the key sequence in between SCF cycles.
Alternatively you can send signal 9 to the process id: `kill -s 9 <pid>` which should kill it right away

**Comment by anbonimus** [comment]
I see. Thank you! I will give it a try.

**Comment by anbonimus** [comment]
Hi, sorry for the late reply. I tried doing it with PySCF only and it only
took about half an hour to run. I really need the PySCFDriver since I need
the number of orbitals stored in the QMolecule object, which I cannot find
in PySCF. Could you take a look at it?

Yours sincerely
Ruiren

**Comment by mrossinek** [comment]
Alright I did a few tests given your code snippet from the issue description:

1. using `pyscf` on its own takes ~1 second on my machine
2. using the `PySCFDriver` of the _latest_ Qiskit Nature (0.5.2) takes ~40 seconds. While that is obviously a lot longer, this is mostly due to the heavy-lifting post-processing around the 2-body integrals being computed and stored.

If you [enable logging](https://qiskit.org/documentation/nature/apidocs/qiskit_nature.logging.html#module-qiskit_nature.logging) you will see that the driver itself runs the actual PySCF computation in roughly the same amount of time as when you use PySCF on its own (again, ~1 second on my machine).

Some improvements have been made to our drivers and the post-processing since the version which you are using so I suggest that you update to the latest version. I also mentioned earlier that you can use a `chkfile` to restart your calculation. But since the bottleneck here is actually this post-processing this will not yield in much improvements.

If you are only after the number of orbitals, you can also very easily obtain that from PySCF. I suggest you look at their documentation: https://pyscf.org/
If that does not help you, you can also always look at the source code for the `PySCFDriver` right here in the Qiskit Nature repository.

**Comment by anbonimus** [comment]
Got it. Thank you so much!

Ruiren
