### ISSUE TITLE
Cannot use .interpret method with MinimumEigensolverResult

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/qiskit-nature#1067]
### Environment

- **Qiskit Nature version**: `0.5.2`
- **Qiskit version**: `0.39.2`
- **Python version**: `3.8.13`
- **Operating system**: `Linux-4.15.0-202-generic-x86_64-with-glibc2.10`

### What is happening?

From the [docs](https://qiskit.org/documentation/nature/stubs/qiskit_nature.second_q.problems.ElectronicStructureProblem.interpret.html#qiskit_nature.second_q.problems.ElectronicStructureProblem.interpret), it seems

```python
ElectronicStructureProblem.interpret
```

Should accept a Qiskit `MinimumEigensolverResult`, but this is not the case.

### How can we reproduce the issue?

Here's a minimal code example that shows the issue in context

```python
from qiskit_nature.second_q.mappers import QubitConverter, ParityMapper
qubit_converter = QubitConverter(ParityMapper())

from qiskit_nature.second_q.drivers import PySCFDriver
driver = PySCFDriver(
    atom="H 0 0 0; H 0 0 0.72"
)
problem = driver.run()
hamiltonian = qubit_converter.convert(problem.second_q_ops()[0])

from qiskit.algorithms import NumPyMinimumEigensolver
sol = NumPyMinimumEigensolver().compute_minimum_eigenvalue(hamiltonian)
real_solution = problem.interpret(sol)
```

Output:
```
TypeError: Cannot construct an EigenstateResult from a result of type, <class 'qiskit.algorithms.minimum_eigen_solvers.minimum_eigen_solver.MinimumEigensolverResult'>.
```

### What should happen?

I expect the code to run without error.

### Any suggestions?

I'm a bit confused, but it seems there are two `MinimumEigensolverResult`s. It looks like the class accepted in [the code](https://github.com/Qiskit/qiskit-nature/blob/e8befeb518f53069a5a784a22968c1b3e1abd09b/qiskit_nature/second_q/problems/eigenstate_result.py#L93) is

```python
qiskit.algorithms.minimum_eigensolvers.minimum_eigensolver.MinimumEigensolverResult
```

whereas ~~`driver.run()`~~ `NumPyMinimumEigensolver.compute_minimum_eigenvalue` returns

```python
qiskit.algorithms.minimum_eigen_solvers.minimum_eigen_solver.MinimumEigensolverResult
```

**Comment by woodsp-ibm** [comment]
The `(minimum_)eigen_solvers` in Terra were refactored to support primitives and are in `(minimum_)eigensolvers` folders (no underscore between eigen and solvers). The pre-existing algorithms are still there, currently pending_deprecation but are planned to be deprecated soon. Nature 0.5.0 in the refactored `second_q` code supports only the new primitive based algorithms. The new folder has the new algorithms and the new results. There is a Numpy classical solver there too compatible with this. So the import, for a compatible solver, should be

>from qiskit.algorithms.minimum_eigensolvers import NumPyMinimumEigensolver

where they need to be imported from the new folder.
(The import from qiskit.algorithms are the pre-existing algorithms - this has to stay that way because of  compatibility).

**Comment by frankharkins** [comment]
@woodsp-ibm ok that makes sense. I've got it working now, thank you!
