### ISSUE TITLE
Update Installation Instructions

### ISSUE THREAD

**Issue by woodsp-ibm** [Qiskit/qiskit-nature#119]
When chemistry was part of Aqua, and Aqua installed by default with qiskit, PySCF was changed to an optional install since it would otherwise install for everyone and some people had problems with their installation and did not even want to use chemistry function.

Given that chemistry is part of nature here, and you still might want to install it for physics or other aspects, maybe leaving PySCF as optional is fine. On the other hand today its mostly chemistry and our tests and tutorials etc use this extensively. So I figured I'd raise this for discussion as to whether we want to go back to having it installed as a dependent, like we had in the past before making it optional for reasons given above, or leave it be as optional....

**Comment by mtreinish** [comment]
I'm generally in favor of making it a requirement, except in pyscf's case specifically there have been several packaging issues over the years which have made it particularly problematic. The biggest of these is that there are no windows wheels available (and no convenient source based installation option for windows users) which means users on windows will not be able to install pyscf unless we specifically exclude windows on the requirements list (which is basically the same as optional). There is also macOS version compatibility, I believe all the recent macOS wheel files depend on >=10.13 which precludes users with older macs who can't install 10.13.

There are also issues with newer releases in the 1.7.x series where using pyscf will break the `time` stdlib modules: https://github.com/pyscf/pyscf/issues/814 (which is why everywhere we install pyscf typically pins it to avoid that issue).

**Comment by woodsp-ibm** [comment]
> we specifically exclude windows on the requirements list (which is basically the same as optional).

This was always the case and what we did do, not much choice here. The chemistry programs like PySCF and PSI4 don't do Windows; there is only PyQuante, which is quite limited and only has a conda pkg, or the commercial product Gaussian.

Given that Nature is predominately chemistry, the rationale of installing it was that you could do chemistry out of the box. Otherwise you have to also do an optional install of one of the drivers no matter the platform.

I agree there are limitations - question is it a positive for most people, given that you choosing now to install chemistry as its not installed by default. In the past I'd agree it was the right choice, just wondering if it still is.

I must admit I was not aware of the `time` issue. It seems like there is a fix in the works once PySCF goes to 2.0

**Comment by woodsp-ibm** [comment]
Thinking about this and informing the users, in the past we used to have more around install. I note that, the docs here, we have an API ref, release notes and tutorials but no installation material specific to this that would note/reference to driver installation material etc. So at least I think we need this, and maybe this can be referenced from the main install of qiskit, as it makes sense, like the other docs here, to keep it separate but at least inform users installing optional aspects of qiskit, like this, optimization etc, that there is specific additional install information.

**Comment by mrossinek** [comment]
We have had some more discussion offline and, if I recall correctly, we have come to the conclusion to keep PySCF as an optional install (for the time being), correct @woodsp-ibm?

**Comment by woodsp-ibm** [comment]
Yes. I had left this open as a reminder to augment the new documentation around installation - we used to have top level text or around optional element with links down to the install information. The latter text still exists in the drivers around installation what it's currently missing is some top level 'getting started' information around the optional install, that 'adds' to the getting started information for qiskit for the application specifics  - in this case Nature. In other words the fix for this issue was documentation improvement. If you want to close this and re-open a new one, or maybe rename the title and give it documentation label thats fine by me.
