### ISSUE TITLE
Fix the scheduled CI runs

### ISSUE THREAD

**Issue by mrossinek** [Qiskit/qiskit-nature#122]
### What is the current behavior?

The scheduled CI runs which execute the `slow_test`s has been failing for the past 10 days.
The failing tests are the following:
```
test.algorithms.ground_state_solvers.test_groundstate_eigensolver.TestGroundStateEigensolver.test_uccsd_hf_qasm
test.algorithms.ground_state_solvers.test_groundstate_eigensolver.TestGroundStateEigensolver.test_uccsd_hf_aer_qasm
```
Although the Aer test passes in some CI runs.

### Steps to reproduce the problem

Nothing special to do. Just run the `slow_test`:
```
% export QISKIT_TESTS="run_slow"; python -m unittest test/algorithms/ground_state_solvers/test_groundstate_eigensolver.py
```

### What is the expected behavior?

The tests should pass.

### Suggested solutions

We need to investigate where exactly the fault lies. It could just be that the seeds changed and the values need to be updated. But I think this may be unlikely.

**Comment by woodsp-ibm** [comment]
The second test listed `test_uccsd_hf_aer_qasm` for me works if I swap the SPSA optimizer for the old one. @Cryoris was going to check whether the default behavior of SPSA changed in the recent update/refactor of it. I tried changing maxiter to see, if it was a difference was there a different value that would pass the test - while I found a value it seemed to oscillate between passing and failing i.e. the behavior of each run was not the same. There was some recent fix over calibration to accommodate changes in cost function but since the test case is the same thing I am not sure if that changed anything - I did not try since.

On the first test `test_uccsd_hf_qasm` swapping out SPSA did not cause the test to pass. However I tried with Aer out of curiosity, since sometimes we see problems in BasicAer arise and that allowed the test to pass. So whether its a BasicAer issue/change underlying the failure I am not sure.

**Comment by woodsp-ibm** [comment]
> The second test listed test_uccsd_hf_aer_qasm for me works if I swap the SPSA optimizer for the old one. 

Turns out I did not set the random seed for aqua when using this SPSA from Aqua. It worked fine, and again today, but I noticed it things were changing between runs on intermediate values. Setting the same seed, 700, and it fails. Now I can get the test to pass by changing the seed to 56 (just was one value that worked). I am double checking other aspects before making any change here but I think things seem ok - partly I am double checking that new SPSA behavior is as expected as deltas it is using during calibration are double what they used to be.
