### ISSUE TITLE
Protein Folding Design

### ISSUE THREAD

**Issue by pbark** [Qiskit/qiskit-nature#150]
Protein folding as the first problem in the sampling problems class. We should design the problem and propose an implementation that will follow up.

**Comment by dlasecki** [comment]
Here is a draft of Protein Folding Design. Feedback is welcome.

![Protein folding (2).png](https://images.zenhubusercontent.com/606c28a45aab8780f8196161/1381d56f-3e05-4dbc-ad40-2ad98a34fa0f)

**Comment by mrossinek** [comment]
I think this design looks quite good!

Since this will lead to a new module parallel to `qiskit_nature.problems.second_quantization` it may be useful to also show a pseudo-code which shows the workflow of this module. Most notable will be the lack of using a `driver`, any `transformers` and (although internally) the `qiskit_nature.operators`.
<details>
<summary>
See also a point about the driver difference I made in a comment on #147.
</summary>

> I would also like to suggest to relocate the entire contents of `qiskit_nature.drivers` into `qiskit_nature.drivers.second_quantization`.
Although this may seem unnecessarily nested it will help with navigation once we add `first_quantization` or `sampling` modules because those will not combine with the existing drivers. Thus, moving them into a `second_quantization` module will make that incompatibility directly clear from the code imports.
</details>

With that said, where would some of the modules you suggest end up? `Peptide` sounds like it is an equivalent to `Molecule`. Also the `Penalties` appear to be related to the modular containers proposed in #148 (at least from a design/philosophy perspective).
