### ISSUE TITLE
Extract `MoleculeDriver`

### ISSUE THREAD

**Issue by mrossinek** [Qiskit/qiskit-nature#165]
### What is the expected enhancement?

As part of #147 I propose to extract the common `Molecule`-based driver initialization into a separate driver implementation. As suggested in the initial proposal, this could look similar to the following:
```python
class MoleculeDriver:
   def __init__(self, molecule, driver_type, driver_kwargs):
      # intitialize stuff

   def run(self):
      driver_cls = getattr(qiskit_nature.drivers, self._driver_type)
      driver = driver_cls.from_molecule(self._molecule)
      for key, value in self._driver_kwargs:
         setattr(driver, key, value)
      return driver.run()
```
More details will need to be figured out as we proceed with the actual implementation in the upcoming weeks.

**Comment by mrossinek** [comment]
While starting a prototype of this implementation I ran into the following inconsistency/problem.

The `BaseDriver` has an `hf_method` init-argument which is supposed to be of type `str` ([1][]).
However, all driver implementations which actually use (PySCF, Psi4, pyquante, Gaussian) expect an `HFMethodType` ([2][]) for this field (e.g. [3][]).
The only case where this is simply initialized with a `str` is in the `GaussianForcesDriver` ([4][]).
This is actually a problem because the bosonic (or rather vibrational) case does not use this `hf_method` at all.

Thus, I propose to do the following:
- remove `hf_method` from `BaseDriver`
- instead move `hf_method` to `FermionicDriver` (might become `ElectronicDriver` [cf. #148])
- at this point we can even rename it properly to be more general (potentially `scf_method`) which allows the more natural inclusion of DFT (or Kohn-Sham) methods (as added in #180)

@woodsp-ibm @pbark Please comment :upside_down_face: 

[1]: https://github.com/Qiskit/qiskit-nature/blob/main/qiskit_nature/drivers/base_driver.py#L34
[2]: https://github.com/Qiskit/qiskit-nature/blob/main/qiskit_nature/drivers/fermionic_driver.py#L24
[3]: https://github.com/Qiskit/qiskit-nature/blob/main/qiskit_nature/drivers/pyscfd/pyscfdriver.py#L55
[4]: https://github.com/Qiskit/qiskit-nature/blob/main/qiskit_nature/drivers/gaussiand/gaussian_forces_driver.py#L72

**Comment by woodsp-ibm** [comment]
It was most likely done as a string in the base class so as not to limit the method their for the future. We already has the enum on PyQuante and PySCF, as part of their native config, but it was added to PSI4 and Gaussian to enable them to be configured as a Molecule (method for their native config is passed as part of their native config). I though the intent was to have a MoleculeDriver that would take a molecule, basis set and method and someway to say which actual 'real' driver it would use and each driver would convert from that to its native format. This is in essence the minimum common config. Now if you want to include a bosonic MoleculeDriver (which we did), since as you say it does not support/need method, for what we have now, how does one do that. We chose to in effect ignore the method but keep it common in the base class. Of course when you have a MoleculeDriver that the user is configuring more directly, then this in essence makes this visible to them which it was not really so before being on some base class.

I was thinking going forwards that BaseDriver would be more back to what it was before we added the common Molecule capability - this being broken out now to a single driver (hence common place) which in turn would use some method, kinda like we have on each driver now, to create the native instance. ElectronicDriver then versus VibrationalDriver becomes more about the result I think (though of course the config is different, which it is anyway even across electronic drivers).

**Comment by mrossinek** [comment]
I understand :+1: But I don't fully see what you are proposing..

I agree, that the `BaseDriver` will be stripped from any references to `Molecule` and therefore will return (at least partially) to what it used to be. With the `MoleculeDriver` being extracted it will require the following inputs:
```python
class MoleculeDriver:
    def __init__(mol: Molecule, basis: str, driver_type: Union[str, BaseDriver], driver_kwargs: Dict[str, Any]) -> None:
        # ...

    def run(self) -> DriverResult:
        # determine driver class
        driver_cls = ...
        # construct instance
        driver = driver_cls.from_molecule(self.mol)
        driver.basis = self.basis
```
Ideally, we could even remove the entire need for `driver_kwargs` and instead (if the user has the need to use some non-default options) require them to pass a partially-initialized driver instance to `driver_type` instead. I.e. something like the following:
```
base_driver = PySCFDriver(method="UHF")
driver = MoleculeDriver(mol, "sto3g", base_driver)
driver.run()  # uses PySCFDriver with UHF method
```
However, this will require a more careful implementation of the `MoleculeDriver.run()` method the instance created by `from_molecule` would somehow need to be combined with the passed instance. However, for the time being this might be over-engineered and the `driver_kwargs` solution is probably the easiest route to go with for the time being.

**Comment by mrossinek** [comment]
My focus was shifted to #167 in favor of this issue. Making that issue my higher priority, I will shift this PR towards a Sprint later this month.
