### ISSUE TITLE
Implement Transformers

### ISSUE THREAD

**Issue by manoelmarques** [Qiskit/qiskit-nature#17]
Migrated from Enterprise Github.
Creator: @mrossinek

The state of the `SecondQuantizedSumOp`-Transformations is the following:

- [ ] Implementation
  - [ ] SeniorityZeroTransformation
  - [x] FreezeCoreTransformation
  - [x] ActiveSpaceTransformation
  - [ ] ParticleHoleTransformation
  - ~TranscorrelatedTransformation~
- [ ] Unittests
  - [ ] SeniorityZeroTransformation
  - [x] FreezeCoreTransformation
  - [x] ActiveSpaceTransformation
  - [ ] ParticleHoleTransformation
  - ~TranscorrelatedTransformation~

Note: this issue may be broken down into several issues as work starts to progress.

**Comment by mrossinek** [comment]
We actually need to implement these transformers *before* the `SecondQuantizedOp` is being created. The reason is that in the process of this creation multiple integral coefficients will map to identical `ParticleOp.label`s and, therefore, a compression (or loss) of information occurs.
However, all of the Transformers mentioned above rely on the complete set of raw information (up-to-now mostly integrals) to be available. Therefore, the interface has been adapted to accomodate this as follows:
![screenshot_1612461565](https://user-images.githubusercontent.com/21973473/106934991-1f30c580-671b-11eb-9878-723621916c8b.png)

A note on the `OrderingRules`: these may be used to prevent misordered application of multiple transformers. One possible source of error is shifting of integral indices after one Transformer has been applied. While this can be mitigated by storing a map of orbital indices, other Transformers may just straight up be incompatible. This can also be encoded in this rule set.

**Comment by mrossinek** [comment]
Converting this to an Epic for the planning of the upcoming release.

**Comment by mrossinek** [comment]
I am closing this Epic in favor of keeping the two separate issues that are left from this: #46 and #48.
Since both of these transformers are fairly low in priority, there is no plan to implement them within a scheduled sprint so I would rather close this and leave the separate transformer issues as "up for grabs" (in fact one of them already has a WIP PR).
