### ISSUE TITLE
Finish the BosonicOp implementation

### ISSUE THREAD

**Issue by manoelmarques** [Qiskit/qiskit-nature#23]
Migrated from Enterprise Github.
Creator: @mrossinek

The current `BosonicOp` is a mere copy of the `FermionicOp` with a search-and-replace of `fermionic` for `bosonic`. The actual mathematics of the implementation need to adapted.

- [ ] adapt the mathematics of the `BosonicOp`
- [ ] unittest all methods

**Comment by manoelmarques** [comment]
Creator: @mrossinek

Pauline and I will look into getting the mathematics of this operator sorted out in early February.

**Comment by mrossinek** [comment]
We had some more discussions offline with regards to the implementation of the `BosonicOp` and `SpinOp` (#22).
Here, I will try to summarize some of these thoughts.

The most general representation of a `BosonicOp` is very similar to that of the `FermionicOp` but differs in the commutation relation with respect to the represented particles. Any additional details of the representation such as a differentiation of modes and modals are imposed upon the operator by the specific problem one is interested in.
Therefore, it is also the task of the problem (which constructs the `BosonicOp` as part of the factory method `second_quantized_operators`) to handle such differentiation during the construction.

That being said, there is no longer a need for the `SpinOp` since it is a mere wrapper of the more general `BosonicOp`. We are therefore likely to remove it in favor of extracting the wrapper logic into the specific problem instances.

However, we also noticed that the `BosonicOp` cannot be constructed from a label which is similar to the style of the `FermionicOp` since it is possible to apply multiple `+` or `-` operations on the same mode. Even if we were to come up with characters for multiple such operations on a single index, the number of these is not really bound and therefore this approach does not scale.
Therefore, we would have to go for an approach such as `[2+]III` where we combine an operator character and a count. However, in doing so we loose all of the benefits which came with a 1D-label representation of our operator. The most important one being that we loose the information of the number of modes given by the length of the label.

This is means, that we need to come up with a better language (and internal representation) for the operators. A basic example could look like the following:
```
BosonicOp('+^2[0]', length=4)
```
which would construct an operator with 4 modes and applies a `+` on the 0th index, twice.
The list of possible operations should include: `+`, `-`, `X`, `Y` and `Z`. The identity no longer needs to be accounted for explicitly (since the language is sparse).

Here are some more requirements and thoughts we should keep in mind:
- the internal representation should be efficient for multiplication of two operators
- it should preserve the order in which operators are chained together

Once we have finalized the `BosonicOp` I would argue that we should adapt the `FermionicOp` to be based on the same language since we don't want our users to have to learn two different languages for different implementations of the same `ParticleOp` interface.

**Comment by mrossinek** [comment]
While we did not strictly implement the `BosonicOp` as described by this issue, we did finish most of the work on the `SpinOp` as part of #68. There is also the `VibrationalSpinOp` variant of this class which will shortly be merged as part of #79. Thus, I am closing this issue.
