### ISSUE TITLE
VQEClient Runtime callback issue

### ISSUE THREAD

**Issue by woodsp-ibm** [Qiskit/qiskit-nature#370]
This was commented as a behavior of the VQEClient on the external Qiskit Slack https://qiskit.slack.com/archives/CB6C24TPB/p1632150351317600

In summary the following seems like incorrect behavior in that the callback is mal-functioning under network error conditions

> It seems when using VQE runtime if there is a web socket drop then the callback function returns empty arrays for the iterations and eigenvalues.

**Comment by Cryoris** [comment]
There's the option to reconnect the callback after the stream broke with `job.stream_results(callback)` though that's something the `VQEClient` would need to take care of since we don't expose the `job`. However I'm not sure if that's the right approach, since users/we aer usually interested in the history and don't care so much about the data being sent back in real time.

**Comment by mrossinek** [comment]
Closing this as per https://github.com/Qiskit/qiskit-nature/pull/1124
