### ISSUE TITLE
Can qiskit nature use a custom Hamiltonian and then uccsd ansatz to operate？

### ISSUE THREAD

**Issue by orihhx** [Qiskit/qiskit-nature#407]
### What is the expected enhancement?
Recently, I want to use qiskit nature for some calculations, but the molecular structure in qiskit cannot satisfy me. Therefore, I have constructed the model and generated the Hamiltonian through a reasonable method, but I can't transfer it into qiskit nature for calculation. I don't know if there is any method to solve this problem? In fact, the custom Hamiltonian can be used for calculation in qiskit, but the ansatz design can only be built with Twolocal. It seems that there is no way to use other ansatz designs such as uccsd. I wonder if there is any solution?

**Comment by mrossinek** [comment]
I tried very hard to keep this in mind while coming up with the new design outlined by #701. I wanted to shortly summarize some key points why this still won't be possible in an immediately straight forward fashion:

- when a user comes with their own qubit operator, that means they will not need any of the following Qiskit Nature modules: `drivers`, `properties`, `operators`, `mappers`, `converters`
- they also cannot use the `transformers` because these are designed to transform objects from the `properties` and `problems` module
- if they want to use an `algorithms` solver, they would need to write a custom `problem` which wraps their qubit operator. However, they would also need to work around the need of a `QubitConverter` instance.
- now, even if they were to do all of the above, they still cannot really make full use of the `circuit` objects provided by Qiskit Nature, because all of these rely on the second-quantized `operators` and (by extension) require a `mappers` object.

If they do not want to use any of Qiskit Nature's `circuit` objects, the end-user is better off to use Qiskit Terra directly.
In the future, we may extract new `algorithm` base classes (as shortly mentioned in #701) at which point this might become possible/simpler. However, until then I am going to close this issue as out-of-scope.
