### ISSUE TITLE
`GroundStateEigensolver.solve()` should be async and return a job id when using real backend

### ISSUE THREAD

**Issue by HuangJunye** [Qiskit/qiskit-nature#441]
### What is the expected enhancement?

Even with Qiskit Runtime, a typical VQE program can take more than one hour to run on a real backend, plus queue time. The currently workflow where result has to wait until `solver.solve(problem)` is done is not very friendly for real backend. I would like to suggest a new workflow that is similar to `backend.run(circuit)` for running QASM jobs.

Current workflow

```python
runtime_vqe_groundstate_solver = GroundStateEigensolver(qubit_converter, runtime_vqe)
runtime_vqe_result = runtime_vqe_groundstate_solver.solve(problem)
```

Proposed workflow
```python
runtime_vqe_groundstate_solver = GroundStateEigensolver(qubit_converter, runtime_vqe)
runtime_vqe_job = runtime_vqe_groundstate_solver.solve(problem)
runtime_vqe_result = runtime_vqe_job.get_result()
```
Or create a new method `submit_job` (or other names) if we don't want to break current API.

```python
runtime_vqe_groundstate_solver = GroundStateEigensolver(qubit_converter, runtime_vqe)
runtime_vqe_job = runtime_vqe_groundstate_solver.submit_job(problem)
runtime_vqe_result = runtime_vqe_job.get_result()
```

**Comment by woodsp-ibm** [comment]
Can you elaborate on what you mean by ` is done is not very friendly for real backend.` I would like to understand the problem that this proposal is solving.

I imagine waiting involves holding a remote socket open, and maybe other remote resources involved with this. Currently the workflow is agnostic to whether a remote or local "algorithm" (e.g. VQE) instance in some form is used. What is the expectation of what is changed by this - after all the get_result() has to "wait" until things are completed (but of course knowing things are remote can periodically pool or otherwise get some async notification of completion). I think a clearer picture of the intended goals here would help. And Nature is not the only application that uses VQE (or other remote entities) so we may need to think more broadly here about things.

**Comment by 1ucian0** [comment]
pinging @HuangJunye about `needs information`

**Comment by woodsp-ibm** [comment]
I will note that the intent going forwards is to move the algorithms over to using the primitives. At this point primitives define an interface and whether they are purely local code or code going over to use some remote backend will end up at the level of the primitive. At this point I would argue the primitives more represent the fundamental interface and should ensure friendliness to the backend, whatever that means, as part of their task of improving overall performance etc

**Comment by HuangJunye** [comment]
Sorry I forgot to reply. Yeah I agree with Steve. I think the perspectives have changed since the introduction of primitives. The behavior of the algorithms will be dictated by the behavior of primitives. 

I am still wrapping my head around the runtime session concepts, but it seems to me that currently implementation of [Sampler](https://qiskit.org/documentation/partners/qiskit_ibm_runtime/stubs/qiskit_ibm_runtime.Estimator.__call__.html#qiskit_ibm_runtime.Estimator.__call__) and [Estimator](https://qiskit.org/documentation/partners/qiskit_ibm_runtime/stubs/qiskit_ibm_runtime.Estimator.html#qiskit_ibm_runtime.Estimator) in `qiskit-ibm-runtime` provider returns results not a job similar to the `GroundStateEigensolver` in nature.

Maybe @ikkoham can chimp in?

**Comment by mrossinek** [comment]
I think now that the refactoring to the primitives is complete, this issue can be closed.

As per the runtime session question, this is off-topic for this thread and (if not yet answered via other channels) should be picked up elsewhere :+1:
