### ISSUE TITLE
Initialize ``Lattice``s with ``networkx.Graph``s

### ISSUE THREAD

**Issue by Cryoris** [Qiskit/qiskit-nature#465]
### What should we add?

It would be nice to allow the initialization on ``Lattice``s not only with retworkx graphs but also with networks graphs. Networkx, to date, still has a lot more features and pre-defined graphs that users have access to, and is probably _the_ standard graph library in Python.

**Comment by mtreinish** [comment]
I agree with everything in this issue, I would appreciate issues being opened on retworkx when you encounter a feature gap. Mainly because we'd like retworkx to be usable everywhere and we can prioritize features needed for a real use case. It's hard to know which functionality to prioritize without requests from users.

As an aside the current dev branch has a bunch of new graph generators, you can see the list here: https://qiskit.org/documentation/retworkx/dev/api.html#generators although I don't think any are really applicable to lattices. @k-tamuraphys has already requested some additional functionality here: https://github.com/Qiskit/retworkx/issues/150#issuecomment-945284818 which might not make it into 0.11 but definitely will be a priority for 0.12.

**Comment by Cryoris** [comment]
This issue is not mainly because I was encountering a particular feature gap, but I was more generally concerned about supporting networkx since it's more standardized 🙂
