### ISSUE TITLE
Implement the FreezeCoreTransformer

### ISSUE THREAD

**Issue by mrossinek** [Qiskit/qiskit-nature#47]
### What is the expected feature?

Add the `FreezeCoreTransformer`.

- [x] actual implementation
- [x] unittests
- [x] documentation

**Comment by mrossinek** [comment]
I would like to discuss what we expect from another Hilbert space-reducing transformer. It is clear, that we do need another implementation because the `ActiveSpaceTransformer` (until now) does not support dipole moment operators.

Thus, I think we have the following requirements:
* support dipole moment operators
* reduce the Hilbert space to a specified set of orbitals
    * do we want this to be specified in the same fashion as an active space for consistency
    * or do we want this to be specify the inactive orbitals (rather than the active ones) which is different *on purpose* in order to differentiate the two transformers?
* this transformer should document properly how it is different from the `ActiveSpaceTransformer` (document the introduced approximation, etc.)
* this transformer should support "core freezing" (removing occupied orbitals) as well as "orbital removal" (removing unoccupied orbitals)

What should we call this transformer? It is more than a `FreezeCoreTransformer` but needs to clearly differentiate itself from the `ActiveSpaceTransformer`.

@pbark @woodsp-ibm Please comment.
@stefan-woerner Please comment on what you think about argument consistency vs. on-purpose differentiation.

**Comment by woodsp-ibm** [comment]
What we had before could arguably be refactored and called an `OrbitalReductionTransformer` Yes documentation should distinguish this doing something like explaining that this removes occupied and/or unoccupied orbitals using an approximate solution as compared to the active space transformer, but unlike the active space transformer, the transformation transforms/retains the dipole integrals.

In my mind it would be nice if the orbital specification, for those orbitals to be acted upon/ or ignore (ie active or inactive) set was the same, unless there is good reason. Otherwise users are going to have to configure things differently. The more flexibility there is here over whether you specify the set you want retained or the set to be removed seems like it would be good. So far we kept most of the orbitals hence stating what we wanted to remove, but the other way round would work better if you were removing more than you kept - though that seems unusual, at least for what has been done so far.

Freeze core is then just the special case of this that simply removes just the occupied core orbitals. I guess it could have a flag saying FreezeCore True/False and then a manual configuration of other orbitals. This saves the user knowing what are the core orbitals are, and would be the most common usage. Removal or other orbitals needs knowledge/care with the molecule in question.

**Comment by mrossinek** [comment]
I started looking into this but made an observation which is contrary to my previous understanding of the freeze core implementation. @woodsp-ibm, maybe you can clarify a few things for me here.

I am not fully understanding what the code at https://github.com/Qiskit/qiskit-nature/blob/master/qiskit_nature/fermionic_operator.py#L589-L604 is doing. So far, I had assumed that the freeze core implementation will just remove the eigenvalues of the h1 integrals and remove the modes accordingly. However, clearly from that code, the effect of the h2 integrals is also taken into account. This results in an energy shift which is numerically identical to that produced by the `ActiveSpaceTransformer`. However, the changes to `h1` are not identical between these two cases which raises the question what exactly the freeze core implementation is doing in the lines linked above, when the values in `h_1` are being changed. What is the rational for those changes?

*A quick note:* for chemical tests based on e.g. H2O, the `h1` integrals are indeed the same. But I wanted to push the boundaries and also tested this on some random (hermitian!) matrices, where I started to see the differences in `h1` mentioned above.

**Comment by woodsp-ibm** [comment]
There are two methods there `fermionic_mode_elimination` and `fermionic_mode_freezing` the former we used on unoccupied orbitals and they were simply removed, the latter on occupied orbitals, and an energy was extracted as the orbitals were removed. That much I think you know though. In terms of the detail of what the code does @antoniomezzacapo originally did that code and he may be able to give you the information you seek as I do not know the details of it.
