### ISSUE TITLE
ElectronicStructureResult missing feature - ground state energy?

### ISSUE THREAD

**Issue by DevelopDaily** [Qiskit/qiskit-nature#508]
### What is the expected enhancement?

I often see this image in published literature. I have studied the class `ElectronicStructureResult` and cannot find a function to retrieve the potential energy value `-432` shown in the image, after running the Qiskit [ground state solver tutorial](https://qiskit.org/documentation/nature/tutorials/03_ground_state_solvers.html). The `optimal_point` from the `ElectronicStructureResult.raw_result` shows a value that is close to` -432` (after unit conversion). But, I am not sure of it. Could you please let me know what is the correct way to get the value? Thanks.

![Hydrogen-molecule-potential_EN](https://user-images.githubusercontent.com/54299975/149447386-a74a4e16-658f-440e-9283-19c2469d55d9.png)

Source: https://commons.wikimedia.org/wiki/File:Hydrogen-molecule-potential_EN.svg

**Comment by mrossinek** [comment]
Given the plot above I assume that you are interested in the _dissociation energy_ of H2 (because the plot appears to be normalized against the potential energy of two separate hydrogen atoms).
If that is indeed the case, then you will only be able to compute this value, using _two_ separate computations:
1. One at the equilibrium distance (`r = 74pm`)
2. And one at the dissociation limit (`r >> 400pm`)

You can then simply subtract the total energies (`ElectronicStructureResult.total_energies[0]`) of the different calculations, convert your units and then should obtain this result.

<hr/>

The `optimal_point` has nothing to do with energy values. This numpy array contains the optimal values for the parameters of your Ansatz. The `ElectronicStructureResult` exposes the chemically interesting values directly so you should not need to look into the `raw_result` (which is simply the result object returned by your `MinimumEigenSolver`). You can check the documentation of the `ElectronicStructureResult` for more details: https://qiskit.org/documentation/nature/stubs/qiskit_nature.results.ElectronicStructureResult.html
