### ISSUE TITLE
QEOM energies differ for Statevector and Qasm simulator

### ISSUE THREAD

**Issue by MariaSapova** [Qiskit/qiskit-nature#52]
### Information

- **Qiskit Aqua version**: 0.8.1
- **Python version**: 3.6.8
- **Operating system**: Ubuntu

### What is the current behavior?

For H2 molecule QEOM excited state energies differ running with Statevector and Qasm simulators.

### Steps to reproduce the problem

Please, run the [gist](https://gist.github.com/MariaSapova/0912242cfb0b6e344d86367330f5e94d)

### What is the expected behavior?

Close excited state energies 

### Suggested solutions

Seems like the problem is somewhere in eval() method, but I'm not sure about that.

**Comment by mrossinek** [comment]
I investigated this bug together with @Cryoris again today but we have not been able to track down the exact cause of it yet.. We opened a PR to fix a sub-issue of this but I am afraid a fix for this issue will not make it into the upcoming release.
I will revisit this again in more detail later.

**Comment by Anthony-Gandon** [comment]
This issue seems to have been solved as a side effect of the new Qiskit release.
The problematic methods for this issue (`eval_op()` and `evaluate_operators()`) have been deprecated and replaced.

The new behaviour of the QEOM calculation does not show this difference between the noisy and state vector "backend" (this has also been replaced): see this [gist](https://gist.github.com/Anthony-Gandon/fe4c4c13acaafb2ad7df351c0ed8ac01)

**Comment by mrossinek** [comment]
Thank you, Anthony! :+1:
