### ISSUE TITLE
GroundStateEigensolver evaluate_operators() works incorrectly with qasm

### ISSUE THREAD

**Issue by MariaSapova** [Qiskit/qiskit-nature#53]
### Information

- **Qiskit Aqua version**: qiskit-master
- **Python version**: 0.3.7
- **Operating system**: Ubuntu

### What is the current behavior?

I investigated my issue Qiskit/qiskit-nature#52, where matrix elements of Q matrix in qEOM were completely incorrect. It turns out that using evaluate_operators() from GroundStateEigensolver produces incorrect expectation values when running with qasm simulator.

### Steps to reproduce the problem

See Qiskit/qiskit-nature#52.
Also there is a more simple case: after running VQE-UCCSD calculation I get optimal parameters for the circuit. If I use evaluate_operators() to get the energy on the optimized circuit, the value is different from the one which I got by VQE procedure.

### What is the expected behavior?

Expectation value of the operator should not strongly depend on the simulator.

### Suggested solutions

I copied the code of construct_expectation() from VQE and it helped me to get results equivalent to the statevector ones.

**Comment by mrossinek** [comment]
Hi @MariaSapova! Sorry for the delay in responding.
I would like to see where the root of this problem lies. Can you please explain what you mean by the following:
> I copied the code of construct_expectation() from VQE and it helped me to get results equivalent to the statevector ones.

I do not understand where exactly you copied that code *into*. I assume you replaced some part of the `GroundStateEigensolver` logic. Is that correct? If yes, where exactly did you plug the method from VQE in?

**Comment by MariaSapova** [comment]
Hi @mrossinek! Thank you for your help.
I prepared a [gist](https://gist.github.com/MariaSapova/cbd2f1f823ed0910c2979101c3ddaa35) for you with a simple example. And also you can have a look at the [qeom case](https://gist.github.com/MariaSapova/0912242cfb0b6e344d86367330f5e94d). I  have rewritten the part of computing mean value, as in my example,  and this helped me to get correct matrix elements for QEOM.  Maybe you can explain me what I am doing wrong with evaluate_operators().

**Comment by mrossinek** [comment]
I don't think you are doing something wrong yourself. I really do think this is a bug which proves to be very difficult to track down right now because of all the code migration happening at the moment.
Could you explain in more detail how exactly you manage to get the correct QEOM results with your `compute_mean_value_qasm` function? I cannot seem to reproduce it and instead obtain the following output from your original QEOM gist:
```
Measured Observable is not composed of only Paulis, converting to Pauli representation, which can be expensive.
Statevector results
[-1.85727503 -1.24458674 -0.88272434 -0.22491344]
Qasm results
[-1.85727503         inf         inf         inf]
Measured Observable is not composed of only Paulis, converting to Pauli representation, which can be expensive.
Statevector results:
{'q_0_0': [-0.6417079334932588], 'm_0_0': [12.697946881863064], 'v_0_0': [15.601953359203058], 'q_0_1': [-2.8148849988804137], 'm_0_1': [2.8948991965476987], 'q_0_2': [-3.53860252928e-07], 'm_0_2': [8.78588615224e-07], 'v_0_2': [4.31468287101e-07], 'q_1_1': [-0.6417079334932588], 'm_1_1': [12.697946881863086], 'v_1_1': [15.601953359203081], 'q_1_2': [1.545636216e-07], 'm_1_2': [-2.339184798372e-06], 'v_1_2': [-1.811473969533e-06], 'q_2_2': [-10.267326935892115], 'm_2_2': [407.6178000421111], 'v_2_2': [249.63125374724913]}
-----
Qasm results:
{'q_0_0': [0.0], 'm_0_0': [-0.721926672399066], 'v_0_0': [0.0], 'q_0_1': [-5.78979839309541], 'm_0_1': [5.78979839309541], 'q_0_2': [0.0], 'm_0_2': [0.0], 'v_0_2': [0.0], 'q_1_1': [0.0], 'm_1_1': [-0.721926672399066], 'v_1_1': [0.0], 'q_1_2': [0.0], 'm_1_2': [0.0], 'v_1_2': [0.0], 'q_2_2': [0.0], 'm_2_2': [0.0], 'v_2_2': [0.0]}
```

Could you please also update all modules to the latest `master` versions? We should compare whether there are some significant differences because I also do not get the `-1.7752856421865268` in your manual test but rather anything ranging from `0.01` to `0.03`..

Given all that, I think we may have to wait until closer to the next release of Qiskit Nature because as things stand now, the code appears to be using classes from Aqua which were already migrated to Terra (and only have bug fixes applied there) but we cannot easily switch the imports of all classes over because currently `UCCSD` is still incompatible with (e.g.) Terra's VQE class.

**Comment by MariaSapova** [comment]
@mrossinek as for QEOM: I reproduced QEOM step by step and substituted the only thing --`evaluate_operators()` by `compute_mean_value` to get correct measurement_results.
![image](https://user-images.githubusercontent.com/71624472/108399674-6b0b6080-722b-11eb-9db4-dd60d1eed01c.png). 

My code looks like:
![image](https://user-images.githubusercontent.com/71624472/108400254-0ef50c00-722c-11eb-8f8a-0455ed04ddb8.png)
It helped and the matrix elements now are correct as well as energies. 
I need some time to update qiskit to the latest `master` version. I'll write to you as soon as I make it so we can compare results.

**Comment by MariaSapova** [comment]
@mrossinek I will send you the notebook with QEOM, when I prepare it and check with the new version.
