### ISSUE TITLE
unexist method of vqe used in adapt_vqe

### ISSUE THREAD

**Issue by ChrisW918** [Qiskit/qiskit-nature#553]
Lately, I was trying to use adapt-vqe to calculate a LiH's ground state energy. However, it reported in the line 104 within 

> adapt-vqe.py

the method get_energy_evaluation is not existing.

**Comment by woodsp-ibm** [comment]
What version of Nature and Terra are you using. The `get_energy_evaluation` exists in main and the latest stable (has been there since 0.18 in Terra). 

There is a unit test here that passes CI that would otherwise fail https://github.com/Qiskit/qiskit-nature/blob/main/test/algorithms/ground_state_solvers/test_adapt_vqe.py
