### ISSUE TITLE
Add a new tutorial: deuteron binding energy

### ISSUE THREAD

**Issue by jvscursulim** [Qiskit/qiskit-nature#559]
### What should we add?

Hi everyone,

I've participated in the project Add Qiskit Nature demonstrations for physics problems (https://github.com/qiskit-advocate/qamp-fall-21/issues/27) of Qiskit Advocate Mentorship Program 2021 Fall, and one of the goals of our group was the development of a tutorial explaining how someone could use Qiskit Nature tools to solve a physical problem. Then, I'm here to present the tutorial about the binding energy in Deuteron that I wrote, and ask you all to take a look and analyze if this work should become a PR and really be considered to be added in the Qiskit Nature tutorials.

Tutorial link: https://github.com/jvscursulim/Qiskit-Tutorials/blob/main/11_deuteron_binding_energy.ipynb

**Comment by pbark** [comment]
Hi @jvscursulim, thank you very much for bringing up this point! I had a look in the notebook and it is really interesting. The only concern I have for now is that in the notebook is more a collection of tools that are used to implement a specific problem and although it is demonstrating how qiskit nature can de used is not directly within the concept of tutorials with follow in qiskit. I would say that you can open a PR so that we can help cleaning up some parts of the code to make them more user friendly and at the same we can try to extract pieces that can possibly be used within the core qiskit Nature code basis. Tagging also @woodsp-ibm!

**Comment by jvscursulim** [comment]
Thanks for the comments @pbark. I'll open the PR with the tutorial.
