### ISSUE TITLE
The specific compositions of a circuit evolution and FermionOp. 

### ISSUE THREAD

**Issue by ChrisW918** [Qiskit/qiskit-nature#581]
### What should we add?

Hi, lately I was trying to calculate a molecule's ground state energy using VQE module, and I am curious about the circuit composition of ansatz and Hamiltonian and expect to compare them with mapping equations. 

However, I encountered an issue that while I tried to draw() the ansatz, it returns a circuit with one component called EvoledOps that units all the operation as a blackbox.
![b8fc127207d7fe8696ca6bd47147338](https://user-images.githubusercontent.com/67126937/155688402-d49fcf38-865f-42d6-bc27-89f4a02a9c53.png)

Also, if I tried to print the FermionOp, `problem.the second_q_ops()`, it merely returns partial results with truncation. 
![0452ca33ba770333a88367fafbf451d](https://user-images.githubusercontent.com/67126937/155690599-5b608c75-3460-497a-b800-b06cc1f85c87.png)

And if I make a loop to check the component of the FermionOp, 
```
for item in problem.second_q_ops():
    for itemy in item.to_list():
        print(itemy)
```
it returns many trivial terms without optimization. In this case, I am printing a LiH molecular, which supposed to carry 92 ops, yet it shows 831 in total. 
![a70e75c462e3d7edb47d781635f2d73](https://user-images.githubusercontent.com/67126937/155689423-57485397-13e7-4d1b-aba0-49d459091c1f.png)

As a result, first I want to understand the structure of a FermionOp object, as I presume some iterations within is necessary and the rest is trivial, so I can determine which specific iteration to check. Secondly, is there an existing method to show an ansatz circuit with all the Pauli operators showing?

**Comment by mrossinek** [comment]
1. A `QuantumCircuit` has a  [decompose](https://qiskit.org/documentation/stubs/qiskit.circuit.QuantumCircuit.decompose.html?highlight=decompose#qiskit.circuit.QuantumCircuit.decompose) method which you can run before drawing. This will grant more insight into the actual structure. To be explicit: `ansatz.decompose().draw()` should do the trick (you may need to `build()` the ansatz first, that depends a bit on how exactly you are constructing `ansatz`).

2. `FermionicOp` does not perform any reductions/simplifications automatically because in certain scenarios the full structure needs to be available. You can run `op.reduce()` manually to reduce the operator.

3. As explained in the [documentation]( https://qiskit.org/documentation/nature/stubs/qiskit_nature.operators.second_quantization.FermionicOp.html#qiskit_nature.operators.second_quantization.FermionicOp) you can use `FermionicOp.set_truncation(0)` to disable the truncation when printing an operator.


Does this answer all your questions?

**Comment by ChrisW918** [comment]
@mrossinek Thanks!

**Comment by ChrisW918** [comment]
Hi @mrossinek ,

first thanks for your answers, and I successfully print the ansatz using `decompose()`. However, I haven't deal with exponential operators on circuit before. As shown in the graph below.
![1d55543c90eb26010c969c560be0fae](https://user-images.githubusercontent.com/67126937/155910326-a2d07b7c-409b-4f33-914f-2729dfeb7e32.png)
Could you help me explaining how these operators mapping on circuit. Taking 

> exp(-i IIYX + IIXY)(1.0*t[0])

 as an example, is it decomposed of several CNOT gates linking every qubit to ancillary bit and a RZ of theta=1.0*t[0] at the centre, just like measuring a Hamiltonian?

**Comment by pbark** [comment]
Hi @ChrisW918 you can further decompose the circuit up to the point that only the basis gates are included. You can do it via `ansatz.decompose().decompose().decompose().draw()`. If you are interested in the theory behind it there are multiple papers that explain this, e.g. [here](https://arxiv.org/pdf/1805.04340.pdf), Section B.II
