### ISSUE TITLE
Deprecate dense labels

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit-nature#610]
### What is the expected enhancement?

Dense labels are confusing to use. I'm sure I'm not the only one who thinks this; I have encountered bugs in other people's code that arose from the use of dense labels. There are two sources of confusion:
1. It is easy to forget to account for the accumulated sign due to permutation of fermionic modes
2. Dense labels in Qiskit Nature use big endian ordering, which is the opposite of Qiskit Terra's convention

Dense labels are not necessary because sparse labels can always be used instead.

**Comment by mrossinek** [comment]
After some offline discussion, I agree that the dense labels are no longer needed since the sparse labels are arguably more useful and less error-prone. As such, their deprecation will:

- avoid future bugs/confusion of users
- de-clutter the code by allowing us to remove various aspects of the code which are only needed for dense labels
- resulting in overall more maintainable code :+1: 

Feel free to go ahead and open a PR which properly deprecates the use of dense labels. We are already announced that the default `display_format` will be changed from `dense` to `sparse` (side note: @ikkoham @manoelmarques did we actually update this already?) so adding another deprecation warning now to fully remove support for `dense` labels in 0.5 or 0.6 (technically required by Qiskit deprecation policy) seems like a good idea :+1:
