### ISSUE TITLE
Refactor VibrationalProblem-related variational forms and initial state

### ISSUE THREAD

**Issue by woodsp-ibm** [Qiskit/qiskit-nature#70]
CHC is currently a VariationalForm. This should be refactored over to circuit/library as a BluePrint circuit

**Comment by mrossinek** [comment]
In fact, once #79 and #66 are merged, we need to migrate all vibrational-related variational forms and initial states. These are:
- [ ] `VSCF`: straight forward like `HartreeFock` (see also #85)
- [ ] `UVCC`: preparations are being done in #66. However, this requires the `VibrationalSpinOp` from #79.
- [ ] `CHC`: should also be rather straight forward because this is already a `QuantumCircuit`. I am not sure whether it will need to become a `BlueprintCircuit`. I need to discuss this with @Cryoris
