### ISSUE TITLE
No module named 'qiskit_nature.second_q'.

### ISSUE THREAD

**Issue by jeb12301** [Qiskit/qiskit-nature#811]
### Environment

- **Qiskit Nature version**:  0.4.1
- **Python version**:  3.9.12
- **Operating system**:  macos catalina 10.15.7

### What is happening?

Python returns: No module named 'qiskit_nature.second_q'. 

I installed qiskit_nature using pip3 install 'qiskit[nature]' as described in the documentation. 

Typing: import qiskit_nature; dir(qiskit_nature) returns:
['ListOrDictType', 'QiskitNatureError', 'UnsupportMethodError', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'exceptions', 'logging', 'settings', 'version']

### How can we reproduce the issue?

<img width="722" alt="image" src="https://user-images.githubusercontent.com/98257374/187035695-5f490674-d909-4320-b66e-0b1e07e85b30.png">

### What should happen?

Should successfully import

**Comment by woodsp-ibm** [comment]
The module `second_q` is new since the official release and is part of the ongoing refactoring work here in the Qiskit Nature repository, in the main branch, and to use this you would have to install from source from this repo off the main branch. See this [Getting Started](https://qiskit.org/documentation/nature/getting_started.html) for details if this is what you want to do. Bear in mind the main branch here is under active development.

The lattice modules exist in the official release too - in their original/current location see the [API ref for the lattices](https://qiskit.org/documentation/nature/stubs/qiskit_nature.problems.second_quantization.lattice.html#module-qiskit_nature.problems.second_quantization.lattice) for further information. This [Lattice Models tutorial](https://qiskit.org/documentation/nature/tutorials/10_lattice_models.html) can also be referenced as it works with the official release and uses them from this location. (They exist in the same place here in main too except they have been deprecated there and will be eventually removed having been replaced by the new ones in second_q location)
