### ISSUE TITLE
give an hamiltonian manually to an ElectronicStructureProblem  

### ISSUE THREAD

**Issue by orielkiss** [Qiskit/qiskit-nature#833]
### What should we add?

Hello,

when using algorithms implemented in qiskit, such as the VQE, it is common practice to use an ElectronicStructureProblem and to use a driver to build the Hamiltonian in second quantization. However, when working on problems outside quantum chemistry, it is difficult to integrate the hamiltonian into the problem instance, because of all the inter dependencies qiskit has. 

To be quick: i have an Hamiltonian written in second quantization, and i would like to wrap it in a Problem instance such that i can then use the VQE implemented in qiskit and all the assocated techniques for quantum chemistry, like UCC and so on. However, if i try to give manually the Hamiltonian to an ElectronicStructureProblem , it produces errors since i do not use a driver. Is there an easy way to bypass this issue or could we create one? 

Thanks you so much
Oriel

**Comment by mrossinek** [comment]
This is exactly what the ongoing refactoring (see #814) is achieving. In fact, you can already do this since #796 got merged to the `main` branch. This will be part of the next release (early November).

I am currently working on the implementation of #666 which will further refactor the `ElectronicEnergy` and `ElectronicStructureProblem` (see TODO comments in the current implementation inside the `qiskit_nature.second_q` stack). I expect to open a PR for this later this week.

I am closing this issue, since the specific functionality requested here was already implemented in the `main` branch as part of #796.

**Comment by orielkiss** [comment]
Thank you Max. 

I am still a bit confused about how to use #796 to be honest. In the case described above, how can i wrap my fermionic operator (so in second quantisation)  into the ElectronicStructureProblem? Or should i use another class? 
Thank you!
