### ISSUE TITLE
Migrate MP2Info

### ISSUE THREAD

**Issue by mrossinek** [Qiskit/qiskit-nature#89]
### What is the expected enhancement?

I already mentioned `qiskit_nature.mp2info` [here](https://github.com/Qiskit/qiskit-nature/pull/66#issuecomment-803277819) because it is still coupled to the old `UCCSD` implementation. Do we need this for the release next week?

@pbark @woodsp-ibm

**Comment by pbark** [comment]
Also discussed in PR #66 , we should keep this since this calculation should be easy to do and provide good initial estimates.

**Comment by mrossinek** [comment]
To clarify: this will not be outright removed. It's refactoring is just postponed until a feature release in the future.

**Comment by woodsp-ibm** [comment]
If we still want it somewhat usable one could copy the old excitation computation code from UCCSD and paste it in the MP2Info for now - later it could be refactored and use some common excitation code that is shared with the current UCCSD

**Comment by mrossinek** [comment]
The code that would be necessary is the most-refactored part of the code. Copying that over is by no means what we should go for here. If you really deem it necessary to be included I can make a push for it on the weekend but I don't see it used anywhere (not even in the tutorials as far as I can tell).

**Comment by woodsp-ibm** [comment]
The mp2info code is not used anywhere. There was a test for it but it was never used by any tutorials or anything. Just left for the user to experiment with since you could compute the coeffs and then use them say with UCCSD. Though as I have mentioned before we were never able to set it such that the resultant energy was the MP2 energy value.
I only suggested copying the excitation code over since that is what it worked with and it would still be standalone and just as it is now with minimal effort.  It seemed that the thought was not to drop if from this release. I was not suggesting to keep it like that more an interim solution, if its wanted to be kept, until it can be better refactored.

**Comment by mrossinek** [comment]
Yes the old excitation code is no longer compatible.
