### ISSUE TITLE
SparseLabelOp doesn't validate input when copy=False

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit-nature#912]
### Environment

- **Qiskit Nature version**: 40f18174ed8246c9d0fa02981ffda7f127c30a45
- **Python version**: N/A
- **Operating system**: N/A

### What is happening?

As you can see, the validation is not performed if copy is False.

https://github.com/Qiskit/qiskit-nature/blob/40f18174ed8246c9d0fa02981ffda7f127c30a45/qiskit_nature/second_q/operators/sparse_label_op.py#L76-L81

### How can we reproduce the issue?

N/A

### What should happen?

Validation should be performed even if copy=False.

**Comment by mrossinek** [comment]
This is done by design to completely avoid having to iterate over the data contents when `copy=False`.
This is also stated in the documentation of both, the `SparseLabelOp` baseclass [here](https://github.com/Qiskit/qiskit-nature/blob/40f18174ed8246c9d0fa02981ffda7f127c30a45/qiskit_nature/second_q/operators/sparse_label_op.py#L63-L66) and the `FerminionicOp` class [here](https://github.com/Qiskit/qiskit-nature/blob/40f18174ed8246c9d0fa02981ffda7f127c30a45/qiskit_nature/second_q/operators/fermionic_op.py#L167-L170).
