### ISSUE TITLE
Construct SparseLabelOp subclasses from list of tuples

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit-nature#954]
### What should we add?

The new version of FermionicOp does not support this yet; see #493 . It should be implemented as a class method.

**Comment by mrossinek** [comment]
To provide a bit more context: the expectation is that a classmethod `from_terms` be added which implements the reverse of the already existing `terms` method.

Feature parity of all operator classes should be ensured and since this is a minor feature I would expect a PR to implement this method for all subclasses of `SparseLabelOp`
